using System.ComponentModel.DataAnnotations;

namespace AwesomeBooks.Model.DomainEntities
{
    public class DomainEntity : IHasId, IHasConcurrencyToken
    {
        /// <summary>
        /// Entity Identifier.
        /// </summary>
        /// <remarks>Entity databse identity is supposed to be generated by database automatically.</remarks>
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Concurrency Token
        /// </summary>
        [Timestamp]
        public byte[] Timestamp { get; set; }

        public override bool Equals(object obj)
        {
            if (obj == null || obj.GetType() != GetType())
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (Id == 0)
            {
                return base.Equals(obj);
            }
            var other = (DomainEntity)obj;
            return Id == other.Id;
        }

        public override int GetHashCode()
        {   
            if (Id == 0)
            {
                return base.GetHashCode();
            }
            return Id.GetHashCode();
        }
    }
}